services:

  postgres:
    image: postgres:16-alpine
    container_name: lace_up_postgres
    restart: unless-stopped
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: lace_up_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: