export const LOCATION_DATA = [
  {
    id: 1,
    name: "Thành phố Hồ Chí Minh",
    districts: [
      {
        name: "Quận 1",
        wards: [
          "Phường Bến Nghé",
          "Phường Bến Thành",
          "Phường Cô Giang",
          "Phường Cầu Kho",
          "Phường Cầu Ông Lãnh",
          "Phường Đa Kao",
          "Phường Nguyễn Thái Bình",
          "Phường Nguyễn Cư Trinh",
          "Phường Phạm Ngũ Lão",
          "Phường Tân Định",
        ],
      },
      {
        name: "Quận 2",
        wards: [
          "Phường An Phú",
          "Phường Thảo Điền",
          "Phường An Khánh",
          "Phường Bình An",
          "Phường Thủ Thiêm",
          "Phường Bình Trưng Đông",
          "Phường Bình Trưng Tây",
          "Phường Thạnh Mỹ Lợi",
          "Phường Cát Lái",
        ],
      },
      {
        name: "Quận 3",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 4",
          "Phường 5",
          "Phường 9",
          "Phường 10",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường Võ Thị Sáu",
        ],
      },
      {
        name: "Bình Thạnh",
        wards: [
          "Phường 1",
          "Phường 2",
          "Phường 3",
          "Phường 5",
          "Phường 6",
          "Phường 7",
          "Phường 11",
          "Phường 12",
          "Phường 13",
          "Phường 14",
          "Phường 15",
          "Phường 17",
          "Phường 19",
          "Phường 21",
          "Phường 22",
          "Phường 24",
          "Phường 25",
          "Phường 26",
          "Phường 27",
          "Phường 28",
        ],
      },
      {
        name: "Quận 4",
        wards: ["Phường 1", "Phường 2", "Phường 3", "Phường 4"],
      },
      {
        name: "Quận 5",
        wards: ["Phường 1", "Phường 2", "Phường 3", "Phường 4"],
      },
      {
        name: "Quận 7",
        wards: ["Phường Tân Kiểng", "Phường Tân Phong", "Phường Tân Quy"],
      },
      {
        name: "Thành phố Thủ Đức",
        wards: [
          "Phường Linh Chiểu",
          "Phường Linh Trung",
          "Phường Hiệp Bình Chánh",
        ],
      },
    ],
  },
  {
    id: 2,
    name: "Hà Nội",
    districts: [
      {
        name: "Ba Đình",
        wards: [
          "Phường Cống Vị",
          "Phường Điện Biên",
          "Phường Đội Cấn",
          "Phường Giảng Võ",
          "Phường Kim Mã",
          "Phường Liễu Giai",
          "Phường Ngọc Hà",
          "Phường Ngọc Khánh",
          "Phường Nguyễn Trung Trực",
          "Phường Phúc Xá",
          "Phường Quán Thánh",
          "Phường Thành Công",
          "Phường Trúc Bạch",
          "Phường Vĩnh Phúc",
        ],
      },
      {
        name: "Hoàn Kiếm",
        wards: [
          "Phường Chương Dương",
          "Phường Cửa Đông",
          "Phường Cửa Nam",
          "Phường Đồng Xuân",
          "Phường Hàng Bạc",
          "Phường Hàng Bài",
          "Phường Hàng Bồ",
          "Phường Hàng Bông",
          "Phường Hàng Buồm",
          "Phường Hàng Đào",
          "Phường Hàng Gai",
          "Phường Hàng Mã",
          "Phường Hàng Trống",
          "Phường Lý Thái Tổ",
          "Phường Phan Chu Trinh",
          "Phường Phúc Tân",
          "Phường Trần Hưng Đạo",
          "Phường Tràng Tiền",
        ],
      },
      {
        name: "Cầu Giấy",
        wards: [
          "Phường Dịch Vọng",
          "Phường Dịch Vọng Hậu",
          "Phường Mai Dịch",
          "Phường Nghĩa Đô",
          "Phường Nghĩa Tân",
          "Phường Quan Hoa",
          "Phường Trung Hòa",
          "Phường Yên Hòa",
        ],
      },
      {
        name: "Đống Đa",
        wards: ["Phường Cát Linh", "Phường Hàng Bột", "Phường Khâm Thiên"],
      },
    ],
  },
  {
    id: 3,
    name: "Đà Nẵng",
    districts: [
      {
        name: "Hải Châu",
        wards: [
          "Phường Hải Châu I",
          "Phường Hải Châu II",
          "Phường Thạch Thang",
          "Phường Thuận Phước",
          "Phường Hòa Thuận Tây",
          "Phường Hòa Thuận Đông",
          "Phường Phước Ninh",
          "Phường Bình Thuận",
          "Phường Bình Hiên",
          "Phường Hòa Cường Bắc",
          "Phường Hòa Cường Nam",
        ],
      },
      {
        name: "Sơn Trà",
        wards: [
          "Phường Thọ Quang",
          "Phường Nại Hiên Đông",
          "Phường Mân Thái",
          "Phường An Hải Bắc",
          "Phường An Hải Tây",
          "Phường An Hải Đông",
          "Phường Phước Mỹ",
        ],
      },
      {
        name: "Ngũ Hành Sơn",
        wards: [
          "Phường Mỹ An",
          "Phường Khuê Mỹ",
          "Phường Hòa Quý",
          "Phường Hòa Hải",
        ],
      },
    ],
  },
];
