server:
  port: ${SERVER_PORT}
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

url:
  backend: ${BACKEND_URL}
  frontend: ${FRONTEND_URL}

spring:
  application:
    name: LaceUP_System_Backend
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mongodb:
    uri: ${SPRING_DATA_MONGODB_URI}
    auto-index-creation: true

  ai:
    model:
      chat: openai
      embedding: google-genai

    openai:
      api-key: ${GROQ_API_KEY}
      base-url: https://api.groq.com/openai
      chat:
        options:
          model: llama-3.3-70b-versatile
          temperature: 0.3

    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        embedding:
          text:
            options:
              model: gemini-embedding-001
              dimensions: 768

    vectorstore:
      pgvector:
        index-type: NONE
        distance-type: COSINE_DISTANCE
        dimensions: 768
        initialize-schema: true

jwt:
  secret-key: ${JWT_SECRET_KEY}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}

token_reset_password_expire_seconds: 900

google:
  client:
    id: ${GOOGLE_ID}
    secret: ${GOOGLE_SECRET}
    uri: ${GOOGLE_URI}

payos:
  client-id: ${PAYOS_CLIENT_ID}
  api-key: ${PAYOS_API_KEY}
  checksum-key: ${PAYOS_CHECKSUM_KEY}
  base-url: https://api-merchant.payos.vn
  return-url: ${PAYOS_RETURN_URL}
  cancel-url: ${PAYOS_CANCEL_URL}

vnpay:
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  pay-url: ${VNPAY_PAY_URL}
  return-url: ${VNPAY_RETURN_URL}
  version: "2.1.0"
  command: "pay"

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}

logging:
  file:
    name: logs/app.log
  level:
    org.sport.backend: INFO

app:
  ai:
    vector:
      threshold: 0.1
      top-k: 2

momo:
  partner-code: ${MOMO_PARTNER_CODE}
  redirect-url: ${MOMO_REDIRECT_URL}
  endpoint: ${MOMO_ENDPOINT}
  ipn-url: ${MOMO_IPN_URL}
  access-key: ${MOMO_ACCESS_KEY}
  secret-key: ${MOMO_SECRET_KEY}
  request-type: ${MOMO_REQUEST_TYPE}

goong:
  api-key: ${GOONG_API_KEY}