
export const VIETNAM_PROVINCES_V2 = [
  { label: "Thành phố Hà Nội", value: "Thành phố Hà Nội" },
  { label: "Thành phố Hồ Chí Minh", value: "Thành phố Hồ Chí Minh" },
  { label: "Thành phố Đà Nẵng", value: "Thành phố Đà Nẵng" },
  { label: "Thành phố Hải Phòng", value: "Thành phố Hải Phòng" },
  { label: "Thành phố Cần Thơ", value: "Thành phố Cần Thơ" },
  { label: "Tỉnh An Giang", value: "Tỉnh An Giang" },
  { label: "Tỉnh Bạc Liêu", value: "Tỉnh Bạc Liêu" },
  { label: "Tỉnh Bến Tre", value: "Tỉnh Bến Tre" },
  { label: "Tỉnh Bình Dương", value: "Tỉnh Bình Dương" },
  { label: "Tỉnh Bình Định", value: "Tỉnh Bình Định" },
  { label: "Tỉnh Bình Phước", value: "Tỉnh Bình Phước" },
  { label: "Tỉnh Bình Thuận", value: "Tỉnh Bình Thuận" },
  { label: "Tỉnh Cà Mau", value: "Tỉnh Cà Mau" },
  { label: "Tỉnh Cao Bằng", value: "Tỉnh Cao Bằng" },
  { label: "Tỉnh Đắk Lắk", value: "Tỉnh Đắk Lắk" },
  { label: "Tỉnh Đắk Nông", value: "Tỉnh Đắk Nông" },
  { label: "Tỉnh Đồng Nai", value: "Tỉnh Đồng Nai" },
  { label: "Tỉnh Đồng Tháp", value: "Tỉnh Đồng Tháp" },
  { label: "Tỉnh Gia Lai", value: "Tỉnh Gia Lai" },
  { label: "Tỉnh Hà Giang", value: "Tỉnh Hà Giang" },
  { label: "Tỉnh Hà Nam", value: "Tỉnh Hà Nam" },
  { label: "Tỉnh Hà Tĩnh", value: "Tỉnh Hà Tĩnh" },
  { label: "Tỉnh Hậu Giang", value: "Tỉnh Hậu Giang" },
  { label: "Tỉnh Hòa Bình", value: "Tỉnh Hòa Bình" },
  { label: "Tỉnh Hưng Yên", value: "Tỉnh Hưng Yên" },
  { label: "Tỉnh Khánh Hòa", value: "Tỉnh Khánh Hòa" },
  { label: "Tỉnh Kiên Giang", value: "Tỉnh Kiên Giang" },
  { label: "Tỉnh Lâm Đồng", value: "Tỉnh Lâm Đồng" },
  { label: "Tỉnh Lạng Sơn", value: "Tỉnh Lạng Sơn" },
  { label: "Tỉnh Lai Châu", value: "Tỉnh Lai Châu" },
  { label: "Tỉnh Nghệ An", value: "Tỉnh Nghệ An" },
  { label: "Tỉnh Ninh Bình", value: "Tỉnh Ninh Bình" },
  { label: "Tỉnh Ninh Thuận", value: "Tỉnh Ninh Thuận" },
  { label: "Tỉnh Quảng Ngãi", value: "Tỉnh Quảng Ngãi" },
];
